# Generated by Django 4.1.7 on 2023-07-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_universitygroup_subjects_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitygroup',
            name='semesters',
            field=models.ManyToManyField(blank=True, to='core.semester'),
        ),
    ]
