# Generated by Django 4.2.2 on 2023-07-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_universitygroup_semesters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitygroup',
            name='semesters',
            field=models.ManyToManyField(to='core.semester'),
        ),
    ]
