# Generated by Django 4.2.2 on 2023-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_universitygroup_semesters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='universitygroup',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
